// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9qSwXoaK30HWVmNYplTricxopLX1bAto',
    appId: '1:259408443986:web:abc768a807952ee8c07d8b',
    messagingSenderId: '259408443986',
    projectId: 'loby-a77e8',
    authDomain: 'loby-a77e8.firebaseapp.com',
    storageBucket: 'loby-a77e8.appspot.com',
    measurementId: 'G-S3VK81E76G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOcp0Pd63bI8q5lD_Pxdr2UpRQQUFbrRc',
    appId: '1:259408443986:android:102ffa3ebb57f77ac07d8b',
    messagingSenderId: '259408443986',
    projectId: 'loby-a77e8',
    storageBucket: 'loby-a77e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkNBQZS_5pjJ9QY3sDkb3SBNP9m-AbyDM',
    appId: '1:259408443986:ios:c97c9b87ca5839bdc07d8b',
    messagingSenderId: '259408443986',
    projectId: 'loby-a77e8',
    storageBucket: 'loby-a77e8.appspot.com',
    iosClientId: '259408443986-9512m0pm2th1tb6etg2r58bod9mr2i5p.apps.googleusercontent.com',
    iosBundleId: 'com.loby.app',
  );
}
