const Map<String, dynamic> walletReason = {
  "SERVICE_ORDERED": "SERVICE ORDERED",
  "DISPUTE_FAVOURED": "DISPUTE FAVOURED",
  "DISPUTE_COMMISSION": "DISPUTE COMMISSION",
  "FUND_ADDED": "FUND ADDED",
  "SETTLEMENT_REQUESTED": "SETTLEMENT REQUESTED",
  "SETTLEMENT_REJECTED": "SETTLEMENT REJECTED",
  "ADMIN": "ADMIN",
  "PAYOUT_FAILED": "PAYOUT FAILED",
  "DUEL_ORDERED": "DUEL ORDERED",
  "DUEL_ACCEPTED": "DUEL ACCEPTED",
  "ORDER_COMPLETED_SUCCESSFULLY": "ORDER COMPLETED SUCCESSFULLY",
  "REFUND_OF_HOLDED_AMOUNT": "REFUND OF HOLDED AMOUNT"
};